### ISSUE TITLE
Use of updateFromResponse on DataProcessor makes undo functionality useless

### ISSUE THREAD

**Issue by k8n** [webix-hub/tracker#312]
When ```updateFromResponse``` is set on DataProcessor and it's master (e.g. datatable) has ```undo``` option set to true, calling ```undo()``` on the data processor or the table has no apparent effect.  That is because saving an item creates two undo history entries, one for the original change and one due to the update from the response. (See line 36896 of webix_debug.js v.5.0.3). So calling the undo() method undoes the update from response, which is useless.

**Comment by Zwillinge** [comment]
Hello,

There seems to be no inconsistency in the updateFromResponse and undo logic: by default, the record is not updated with response data if a save error occurs (response status is 400 or bigger or you return status:"error"/"invalid" in JSON).

So, the following combination works smoothly with the current 5.3 version: 

~~~js
view:"datatable",
undo:true,
save: {
	undoOnError:true,
	updateFromResponse:true,
	url:"..."
}
~~~

Please note that if you define a custom handler for DataProcessor "onBeforeSaveError" event (in which you are possibly calling the .undo() explicitely), be sure not to return false in it, as otherwise updateFromResponse logic may be executed.
